### ISSUE TITLE
Djangonaut getting enabled even when not in a django project

### ISSUE THREAD

**Issue by aiguofer** [proofit404/djangonaut#11] opened 2020-04-15 23:21 UTC
Looks like `(when (djangonaut-get-project-root)` call in `(define-globalized-minor-mode global-djangonaut-mode djangonaut-mode)` always returns true.

When I do `M-: (djangonaut-get-project-root)` I just get the string of the error:

```
"Traceback (most recent call last):
  File \"<string>\", line 8, in <module>
  File \"/Users/Diego/.pyenv/versions/engagement/bin/../lib/python3.7/os.py\", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'DJANGO_SETTINGS_MODULE'
"
```

One easy fix could be to change `djangonaut-get-project-root-code` to
```
from __future__ import print_function
from importlib import import_module
from os import environ
from os.path import dirname
import sys
try:
    settings_module = environ['DJANGO_SETTINGS_MODULE']
except KeyError:
    sys.exit(1)
package_name = settings_module.split('.', 1)[0]
package = import_module(package_name)
project_root = dirname(dirname(package.__file__))
print(project_root, end='')
```

**Comment by dakra** [comment] 2020-04-16 07:43
If you activate `global-djangonaut-mode` then this is active globally and decided per buffer if `djangonaut-mode` should be activated or not.

For me this works because there already is an `ignore-errors` around that activation function,
you sure you didn't mix up looking at the global mode when checking?

E.g. `global-djanonaut-mode` is always `t` as it should be?

**Comment by dakra** [comment] 2020-04-16 07:52
BTW, I personally don't activate global modes when I'm only using them in some buffers.
Imho it's better to activate it per project. I.e. I have a `.dir-locals.el` in the root folder most of the time anyway to specify my local settings and I just activate djangonaut from there for django project.
Could look something like:

```emacs-lisp
((nil . ((python-shell-process-environment . ("DJANGO_SETTINGS_MODULE=some_project.settings.base"))
         (mode . djangonaut)))
 (web-mode . ((eval . (web-mode-set-engine "django")))))
```

**Comment by aiguofer** [comment] 2020-04-16 15:48
Sorry, yes this is with `global-djangonaut-mode` enabled. The error here is that the "decided per buffer if djangonaut-mode should be activated or not" part is not working as expected. Calling `(djangonaut-get-project-root)` always returns something, so it always enables `django-mode` (even in non-python buffers). I'm wondering if it would make sense to instead look for a `manage.py` file to determine the root?

**Comment by dakra** [comment] 2020-04-16 19:28
I'm currently not using Django anymore but I worked on a project some time ago where there's no `manage.py` or it is "hidden" in some subfolder and the root is a collection of packages.

But I just tested the global-mode again and for me it's correctly recognizing django projects.
So if I activate `global-djangonaut-mode` and then visit a non Django project Python file
I don't have the Django Menu items or djangonaut keymap.
But when I then go to a Django project, it is there and keymap active.

If you're wondering why djangonaut is even for non Python files active (inside a Django project) then that's by design as you should be able to execute manage command (like migrations etc) from any file and also jump to views etc from any file like a html file. So djangonaut is not Python only.

**Comment by dakra** [comment] 2020-04-24 10:47
I'm closing this issue for now. But feel free to re-open or write more.
I'm currently not working on any Django project so it's definitely possible that there are bugs.

**Closed as completed by dakra** 2020-04-24 10:47 UTC
